#!/bin/csh
####
#
#
set PYPROG = `which python3`
*
set curdir = $PWD
#
if ( -e ${curdir}/clem4cina.py ) then
  set clemscript = ${curdir}/clem4cina.py
else
  if ( -e ~/Projects/clem4cina/clem4cina.py ) then
    set clemscript = ~/Projects/clem4cina/clem4cina.py
  else
    if ( -e ~/Documents/Projects/Softwares/clem4cina/clem4cina.py ) then
      set clemscript = ~/Documents/Projects/Softwares/clem4cina/clem4cina.py
    else
      echo "clem4cina.py script not found."
      exit -1
    endif
  endif
endif
#
if ( "${PYPROG}x" == "python3: Command not found.x" ) then
  set PYPROG = `which python`
endif
# echo "Python is at "${PYPROG}
if ( -e ${PYPROG} ) then
  echo " "
  # echo "Running ${PYPROG} ${clemscript}"
  echo "Running" zsh -c ${PYPROG} ${clemscript}
  echo zsh -c \'${PYPROG} ${clemscript}\' > runcommand.TMP1239877
  chmod +x runcommand.TMP1239877
  echo " "
  source runcommand.TMP1239877
  \rm runcommand.TMP1239877
else
  echo "Python interpreter not found: ${PYPROG}"
  exit -1
endif

#
#
